### ISSUE TITLE
console test fails

### ISSUE THREAD

**Issue by plweil** [lysender/pagecache#6]
I need page caching (using Kohana 3.1), but can't get these rewrite rules to work. I'm using the exact rules in the ReadMe, except for two changes necessitated by placing the rules inside a Virtual Host rather than .htaccess: {DOCUMENT_ROOT}/%{REQUEST_FILENAME}  and a slash before index.php. Apache rewrites are not exactly my forte, so if you can provide any clues as to where to look to resolve this, I'd greatly appreciate it. The mdedia/pagecache/console/test/index.html file is being created, but the test fails ("Two sub-sequent requests return different contents.". And thanks for all of your great blog posts on Kohana (exceptions, validation, etc.) 

My rewrite rules:
## BEGIN Page cache

RewriteRule ^/(.*)/$ /$1 [QSA]
RewriteRule ^$ media/pagecache/index.html [QSA]
RewriteRule ^([^.]+)/$ media/pagecache/$1/index.html [QSA]
RewriteRule ^([^.]+)$ media/pagecache/$1/index.html [QSA]

 # END Page cache

 # Protect application and system files from being viewed
RewriteRule ^(?:application|modules|system)\b - [F,L]

RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_FILENAME} -s [OR]
RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_FILENAME} -l [OR]
RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_FILENAME} -d

RewriteRule ^._$ - [NC,L]
RewriteRule ^._$ /index.php [NC,L]

**Comment by lysender** [comment]
Thank you for filing a ticket. Will check this issue.

**Comment by lysender** [comment]
wontfix
