### ISSUE TITLE
ErrorException [ Error ]: Class 'Pagecache' not found

### ISSUE THREAD

**Issue by electroheadfx** [lysender/pagecache#7]
I think there is a probleme between Xvp and Pagecache namespace ...

Iam on FuelPHP 1.6 Master

**Comment by lysender** [comment]
This module is a Kohana module. What is Xvp by the way?

**Comment by electroheadfx** [comment]
Sorry Iam on the wrong repo :(

**Comment by lysender** [comment]
Yeah, sorry about that. This module is built just for Kohana.
